FifthTry/admint.io

header.ftd

Fixing build issue of image location

---

docs/hero.ftd
docs/index.ftd
lib.ftd

I have added mobile condition to change width of hero component text. As per UI review by @gargajit I have made these changes.

Updating hero UI broken issue on various resolutions

---

FASTN.ftd
docs/footer.ftd
lib.ftd

@gargajit Please, review `footer` documentation.
@Heulitig Please, review.

Added footer documenation

---

common/fonts.ftd
index.ftd
lib.ftd

With this PR added shadow to `lezgoo` component and added `backckground-color` to other components.

Fixing UI review and box shadow

---

index.ftd

Fixing build issue of image name wrong.

Fixing build issue

---

functions.js

Fixing pricing page blur issue. Also, updated JS conditions with ternary operator.

Fixing pricing page blur css

---

common/fonts.ftd
functions.js
learn/brand-campaigns-lorem-ipsum-is-simply-dummy-text-2.ftd
learn/index.ftd
learn/lorem-ipsum-is-simply-dummy-text.ftd
learn/metaverse-is-the-new-playground-for-advertisement-2.ftd
learn/metaverse-is-the-new-playground-for-advertisement.ftd
learn/search-results.ftd
lib.ftd

Added new posts pages. Also, updating tabs links also added page titles. Component width fixes.

Learn tabs links fixes

---

learn/lorem-ipsum-is-simply-dummy-text.ftd
learn/metaverse-is-the-new-playground-for-advertisement-2.ftd
learn/metaverse-is-the-new-playground-for-advertisement.ftd
learn/no-search-results.ftd

With this PR fixing all broken links found on learn pages.

Fixing broken links found on live

---

FASTN.ftd
docs/faq.ftd

With this PR we are updating favicon icon url with https. in docs/faq wrong eng corrected.

Updated favicon url with https

---

common/fonts.ftd
lib.ftd

build fixes

---

FASTN.ftd
docs/sign-up-popup.ftd

With this PR we are adding sign-up-form-popup documentation and updating its link into sitemap.

Docs signup popup

---

FASTN.ftd
docs/advertising-web-3-0.ftd
docs/blog.ftd
docs/brand-campaign.ftd
docs/pricing.ftd
docs/privacy-policy.ftd
docs/terms-conditions.ftd
docs/why-nfts.ftd

With this PR we are adding WIP of documentation page.

added missing and WIP docs links and pages

---

FASTN.ftd
common/fonts.ftd
common/index.ftd
docs/footer-1.ftd
docs/footer-2.ftd
learn/advertising-web-3-0.ftd
learn/brand-campaign.ftd
learn/brand-campaigns-lorem-ipsum-is-simply-dummy-text-2.ftd
learn/index.ftd
learn/lorem-ipsum-is-simply-dummy-text.ftd
learn/metaverse-is-the-new-playground-for-advertisement-2.ftd
learn/metaverse-is-the-new-playground-for-advertisement.ftd
learn/no-search-results.ftd
learn/search-results.ftd
lib.ftd

With this PR we have added `footer-tiny` component and added its docs and updated on relevant pages.

Added new footer-2 and its docs and updated on pages

---

index.ftd
lib.ftd

With this PR added show-signup boolean to show signup popup.

added click event of show-signup

---

FASTN.ftd
common/fonts.ftd

change dependency from nunito to admint nunito

change dependency from nunito to admint nunito

---

common/fonts.ftd
lib.ftd

header-fixes

---

common/fonts.ftd
common/index.ftd
index.ftd
lib.ftd

slider fixes

---

common/fonts.ftd
index.ftd
lib.ftd

Hero fixes

---

common/fonts.ftd
common/index.ftd
lib.ftd

How it works slider fixes

---

docs/advertisement-cards.ftd
docs/help-banner.ftd
docs/how-it-works.ftd
docs/join-waitlist-form.ftd
docs/sneak-peak.ftd

Fixing building issues with new `ftd.container` changes

Fixing docs build issue due to new changes

---

common/fonts.ftd
docs/join-waitlist-popup.ftd
index.ftd
lib.ftd

Px to px match

---

index.ftd
lib.ftd

With this PR, we have compared:
1. Large screen - all slider - slides - Px to Px matched
2. Mac screen - all slider - slides - Px to Px matched
3. Footer thumbs up image - fixed
4. Sneak Peak - fixed

Px to Px - UI Review fixes

---

about.ftd
common/fonts.ftd
index.ftd
lib.ftd

About us fixes

---

common/fonts.ftd
lib.ftd

With this PR we are matching pricing page px to px for desktop version

Fixing pricing page px to px matching

---

FASTN.ftd
docs/about-us.ftd

With this PR we are fixing build issue ocured due to about-us page docs not updated, with latest updates.

Fixing docs of about-us page component with latest changes

---

lib.ftd

With this PR we are fixing slider arrow size and position.

Updated slider arrow image size and position

---

about.ftd
common/fonts.ftd
docs/our-team.ftd
lib.ftd

With this PR we have finished UI review matching px to px for about us page.

About us px to px

---

common/fonts.ftd
lib.ftd

slide fixes

---

common/fonts.ftd
learn/index.ftd
lib.ftd
static/faq/down.svg
static/faq/up.svg

learn-page-fixes

---

learn/index.ftd
lib.ftd

learn page

---

learn/advertising-web-3-0.ftd
lib.ftd

Added inset-body condition

---

common/fonts.ftd
index.ftd
learn/advertising-web-3-0.ftd
lib.ftd

hero page fixes

---

lib.ftd

minor fixes

---

lib.ftd

fixing why nft minor ui

---

lib.ftd

Fixing join waitlist popup

---

lib.ftd
terms-conditions.ftd

Terms and conditions

---

common/fonts.ftd
index.ftd
lib.ftd

mobile fixes homepage

---

lib.ftd

With this PR we are fixing slider issue of STEP title

fixing slider STEP text issue

---

common/fonts.ftd
lib.ftd

brand-campaign mobile version fixes

brand-campaign mobile version fixes

---

lib.ftd

mobile view in brand campaign

---

common/fonts.ftd
lib.ftd

sneak peak mobile fixes

---

lib.ftd

footer-fixes
